--- #YAML:1.0
name:                Term-Size-Any
version:             0.001
abstract:            Retrieve terminal size
license:             perl
author:              
    - Adriano R. Ferreira <ferreira@cpan.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Devel::Hide:                   0
    Module::Load::Conditional:     0
    Term::Size::Perl:              0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
